cmake_minimum_required(VERSION 2.8)

PROJECT(dmrapidpool)

LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
INCLUDE(cmake/ModuleImport.cmake)
INCLUDE(cmake/ModuleCompileOptions.cmake)
ModuleSetCompileOptions()

ADD_DEFINITIONS(-DUSE_DMRAPIDPOOL)

IF (WIN32)
    INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/src/windows)
ENDIF(WIN32)

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/include)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/src)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/test)

FILE(GLOB_RECURSE DMRAPIDPOOL_SOURCES
${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp
${CMAKE_CURRENT_SOURCE_DIR}/include/*.h

${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
${CMAKE_CURRENT_SOURCE_DIR}/src/*.cc
${CMAKE_CURRENT_SOURCE_DIR}/src/*.c
${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp
${CMAKE_CURRENT_SOURCE_DIR}/src/*.h
)

IF (WIN32)
    LIST(APPEND DMRAPIDPOOL_SOURCES)
ENDIF(WIN32)

FILE(GLOB_RECURSE DMRAPIDPOOLTEST_SOURCES
${CMAKE_CURRENT_SOURCE_DIR}/test/*.cpp
${CMAKE_CURRENT_SOURCE_DIR}/test/*.cc
${CMAKE_CURRENT_SOURCE_DIR}/test/*.c
${CMAKE_CURRENT_SOURCE_DIR}/test/*.hpp
${CMAKE_CURRENT_SOURCE_DIR}/test/*.h)

IF (WIN32)
    ADD_LIBRARY(dmrapidpool STATIC ${DMRAPIDPOOL_SOURCES})
    ADD_EXECUTABLE(dmrapidpooltest ${DMRAPIDPOOLTEST_SOURCES})
    TARGET_LINK_LIBRARIES(dmrapidpooltest dmrapidpool)
ELSEIF (APPLE)
    ADD_LIBRARY(dmrapidpool STATIC ${DMRAPIDPOOL_SOURCES})
    ADD_EXECUTABLE(dmrapidpooltest ${DMRAPIDPOOLTEST_SOURCES})
    TARGET_LINK_LIBRARIES(dmrapidpooltest dmrapidpool)
ELSEIF (UNIX)
    ADD_LIBRARY(dmrapidpool STATIC ${DMRAPIDPOOL_SOURCES})
    ADD_EXECUTABLE(dmrapidpooltest ${DMRAPIDPOOLTEST_SOURCES})
    TARGET_LINK_LIBRARIES(dmrapidpooltest dmrapidpool)
ENDIF ()

#ADD_CUSTOM_COMMAND(
#TARGET dmrapidpooltest
#PRE_BUILD
#COMMAND ${CMAKE_COMMAND} -E copy_if_different
#${CMAKE_CURRENT_SOURCE_DIR}/config/test.csv
#$<TARGET_FILE_DIR:dmrapidpooltest>
#)

#INSTALL(DIRECTORY include/ DESTINATION include)
#INSTALL(TARGETS dmrapidpool
#        RUNTIME DESTINATION bin
#        LIBRARY DESTINATION lib
#        ARCHIVE DESTINATION lib)

#SET(DMRAPIDPOOL_LIBS "dmrapidpool")
#MARK_AS_ADVANCED(${DMRAPIDPOOL_LIBS})